/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CennikRouteImport } from './routes/cennik'
import { Route as KontoRouteImport } from './routes/konto'
import { Route as NaTelefonRouteImport } from './routes/na-telefon'
import { Route as NoweRouteImport } from './routes/nowe'
import { Route as OpinieRouteImport } from './routes/opinie'
import { Route as PrywatnoscRouteImport } from './routes/prywatnosc'
import { Route as RaportRouteImport } from './routes/raport'
import { Route as RegulaminRouteImport } from './routes/regulamin'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CennikRoute = CennikRouteImport.update({
  id: '/cennik',
  path: '/cennik',
  getParentRoute: () => rootRouteImport,
} as any)
const KontoRoute = KontoRouteImport.update({
  id: '/konto',
  path: '/konto',
  getParentRoute: () => rootRouteImport,
} as any)
const NaTelefonRoute = NaTelefonRouteImport.update({
  id: '/na-telefon',
  path: '/na-telefon',
  getParentRoute: () => rootRouteImport,
} as any)
const NoweRoute = NoweRouteImport.update({
  id: '/nowe',
  path: '/nowe',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinieRoute = OpinieRouteImport.update({
  id: '/opinie',
  path: '/opinie',
  getParentRoute: () => rootRouteImport,
} as any)
const PrywatnoscRoute = PrywatnoscRouteImport.update({
  id: '/prywatnosc',
  path: '/prywatnosc',
  getParentRoute: () => rootRouteImport,
} as any)
const RaportRoute = RaportRouteImport.update({
  id: '/raport',
  path: '/raport',
  getParentRoute: () => rootRouteImport,
} as any)
const RegulaminRoute = RegulaminRouteImport.update({
  id: '/regulamin',
  path: '/regulamin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/konto': typeof KontoRoute
  '/na-telefon': typeof NaTelefonRoute
  '/nowe': typeof NoweRoute
  '/opinie': typeof OpinieRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/raport': typeof RaportRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/konto': typeof KontoRoute
  '/na-telefon': typeof NaTelefonRoute
  '/nowe': typeof NoweRoute
  '/opinie': typeof OpinieRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/raport': typeof RaportRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cennik': typeof CennikRoute
  '/konto': typeof KontoRoute
  '/na-telefon': typeof NaTelefonRoute
  '/nowe': typeof NoweRoute
  '/opinie': typeof OpinieRoute
  '/prywatnosc': typeof PrywatnoscRoute
  '/raport': typeof RaportRoute
  '/regulamin': typeof RegulaminRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cennik'
    | '/konto'
    | '/na-telefon'
    | '/nowe'
    | '/opinie'
    | '/prywatnosc'
    | '/raport'
    | '/regulamin'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cennik'
    | '/konto'
    | '/na-telefon'
    | '/nowe'
    | '/opinie'
    | '/prywatnosc'
    | '/raport'
    | '/regulamin'
  id:
    | '__root__'
    | '/'
    | '/cennik'
    | '/konto'
    | '/na-telefon'
    | '/nowe'
    | '/opinie'
    | '/prywatnosc'
    | '/raport'
    | '/regulamin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CennikRoute: typeof CennikRoute
  KontoRoute: typeof KontoRoute
  NaTelefonRoute: typeof NaTelefonRoute
  NoweRoute: typeof NoweRoute
  OpinieRoute: typeof OpinieRoute
  PrywatnoscRoute: typeof PrywatnoscRoute
  RaportRoute: typeof RaportRoute
  RegulaminRoute: typeof RegulaminRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cennik': {
      id: '/cennik'
      path: '/cennik'
      fullPath: '/cennik'
      preLoaderRoute: typeof CennikRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/konto': {
      id: '/konto'
      path: '/konto'
      fullPath: '/konto'
      preLoaderRoute: typeof KontoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/na-telefon': {
      id: '/na-telefon'
      path: '/na-telefon'
      fullPath: '/na-telefon'
      preLoaderRoute: typeof NaTelefonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nowe': {
      id: '/nowe'
      path: '/nowe'
      fullPath: '/nowe'
      preLoaderRoute: typeof NoweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinie': {
      id: '/opinie'
      path: '/opinie'
      fullPath: '/opinie'
      preLoaderRoute: typeof OpinieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prywatnosc': {
      id: '/prywatnosc'
      path: '/prywatnosc'
      fullPath: '/prywatnosc'
      preLoaderRoute: typeof PrywatnoscRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raport': {
      id: '/raport'
      path: '/raport'
      fullPath: '/raport'
      preLoaderRoute: typeof RaportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regulamin': {
      id: '/regulamin'
      path: '/regulamin'
      fullPath: '/regulamin'
      preLoaderRoute: typeof RegulaminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CennikRoute: CennikRoute,
  KontoRoute: KontoRoute,
  NaTelefonRoute: NaTelefonRoute,
  NoweRoute: NoweRoute,
  OpinieRoute: OpinieRoute,
  PrywatnoscRoute: PrywatnoscRoute,
  RaportRoute: RaportRoute,
  RegulaminRoute: RegulaminRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
